### ISSUE TITLE
webhook secret

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data-classification-algae-patch#1]
Hi @mdoering could you please help me adding an adequate secret to this repo, I used the same from de the other COL patch wich I'm guessing was a  bad call.

<img width="834" alt="Captura de pantalla 2024-10-03 a la(s) 5 21 34 p m" src="https://github.com/user-attachments/assets/a964b36b-223c-4798-9d7e-69024c3d9a93">

**Comment by mdoering** [comment]
done
